# Site settings
title: T4S
email: annmarie.jahn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  T4S Consulting is a independent consulting firm that helps businesses: 
    Develop and launch new products, both digital and hardgoods.
    Increase revenue and improve profitability.
    Discover, evaluate and pivot to powerful new opportunities
    Achieve your business goals, even in tough economic times
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://time4success-consulting.com"
twitter_username: annmjahn
github_username:  ann-marie-jahn

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "blog/page:num"